# Generated by Django 2.1.5 on 2019-01-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_index',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
