# Generated by Django 2.1.5 on 2019-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_publication_publication_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='id',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_index',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
