# Generated by Django 2.1.5 on 2019-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_auto_20190126_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_index',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_index',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
